=== LMSC-NTappy/agros2d/resources/xsd/module_xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
  <xs:element name="module">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="general" maxOccurs="1"/>
        <xs:element ref="constants" maxOccurs="1"/>        
        <xs:element ref="volume" maxOccurs="1"/>
        <xs:element ref="surface" maxOccurs="1"/>
        <xs:element ref="preprocessor" maxOccurs="1"/>
        <xs:element ref="postprocessor" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="general">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element ref="analyses"/>
      </xs:sequence>
      <xs:attribute name="deformed_shape" type="xs:integer"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="description" type="xs:string"/>
  <xs:element name="analyses">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="analysis"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="analysis">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="solutions" use="required" type="xs:integer"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="constants">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="constant"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="constant">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:double"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="macros">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="macro"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="macro">
    <xs:complexType>
      <xs:attribute name="expression" use="optional" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="preprocessor">
    <xs:complexType>
      <xs:sequence>
  	    <xs:element maxOccurs="unbounded" ref="gui"/>
	  </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="gui">
    <xs:complexType>
      <xs:sequence>
  	    <xs:element maxOccurs="unbounded" ref="group"/>
	  </xs:sequence>
      <xs:attribute name="type" use="required" type="xs:string"/>	  
    </xs:complexType>
  </xs:element>
  
  <xs:element name="postprocessor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="localvariables"/>
        <xs:element ref="view"/>
        <xs:element ref="volumeintegrals"/>
        <xs:element ref="surfaceintegrals"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="localvariables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="localvariable"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="localvariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="expression"/>
      </xs:sequence>
      <xs:attribute name="format" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="shortname" use="required" type="xs:string"/>
      <xs:attribute name="shortname_html" type="xs:string"/>
      <xs:attribute name="shortname_latex" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="unit" use="required" type="xs:string"/>
      <xs:attribute name="unit_html" type="xs:string"/>
      <xs:attribute name="unit_latex" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="view">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="scalar_view"/>
        <xs:element ref="vector_view"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="scalar_view">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="default"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="vector_view">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="default"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="volumeintegrals">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="volumeintegral"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="volumeintegral">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="expression"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="shortname" use="required" type="xs:string"/>
      <xs:attribute name="shortname_html" type="xs:string"/>
      <xs:attribute name="shortname_latex" type="xs:string"/>
      <xs:attribute name="unit" use="required" type="xs:string"/>
      <xs:attribute name="unit_html" type="xs:string"/>
      <xs:attribute name="unit_latex" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="surfaceintegrals">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="surfaceintegral"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="surfaceintegral">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="expression"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="shortname" use="required" type="xs:string"/>
      <xs:attribute name="shortname_html" type="xs:string"/>
      <xs:attribute name="shortname_latex" type="xs:string"/>
      <xs:attribute name="unit" use="required" type="xs:string"/>
      <xs:attribute name="unit_html" type="xs:string"/>
      <xs:attribute name="unit_latex" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="volume">
    <xs:complexType>
       <xs:sequence>
         <xs:element maxOccurs="unbounded" ref="quantity"/>
         <xs:element ref="weakforms_volume"/>
       </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="surface">
    <xs:complexType>
        <xs:sequence>
          <xs:element maxOccurs="unbounded" ref="quantity"/>
          <xs:element minOccurs="1" maxOccurs="1" ref="weakforms_surface"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="weakforms_surface">
    <xs:complexType>
	  <xs:choice>
	    <xs:element ref="group"/>
	  	<xs:sequence>
	   	  <xs:element minOccurs="1" maxOccurs="unbounded" ref="weakform_surface"/>
	    </xs:sequence>
	  </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="weakform_surface">
    <xs:complexType>
      <xs:choice>
        <xs:element maxOccurs="unbounded" ref="boundary"/>
        <xs:sequence>
          <xs:element maxOccurs="unbounded" ref="quantity"/>
          <xs:choice maxOccurs="unbounded">
            <xs:element ref="matrix_form"/>
            <xs:element ref="vector_form"/>
          </xs:choice>
        </xs:sequence>
      </xs:choice>
      <xs:attribute name="analysistype" use="required" type="xs:string"/>
      <xs:attribute name="default" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="expression">
    <xs:complexType>
      <xs:attribute name="analysistype" use="required" type="xs:string"/>
      <xs:attribute name="axi" type="xs:string"/>
      <xs:attribute name="axi_r" type="xs:string"/>
      <xs:attribute name="axi_z" type="xs:string"/>
      <xs:attribute name="planar" type="xs:string"/>
      <xs:attribute name="planar_x" type="xs:string"/>
      <xs:attribute name="planar_y" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="default">
    <xs:complexType>
      <xs:attribute name="analysistype" use="required" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="quantity">
    <xs:complexType>
      <xs:attribute name="condition" type="xs:string"/>
      <xs:attribute name="default" type="xs:decimal"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="nonlin" type="xs:integer"/>
      <xs:attribute name="shortname" type="xs:string"/>
      <xs:attribute name="shortname_html" type="xs:string"/>
      <xs:attribute name="shortname_latex" type="xs:string"/>
      <xs:attribute name="timedep" type="xs:integer"/>
      <xs:attribute name="unit" type="xs:string"/>
      <xs:attribute name="unit_html" type="xs:string"/>
      <xs:attribute name="unit_latex" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="weakforms_volume">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="weakform_volume"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="weakform_volume">
    <xs:complexType>
      <xs:choice>
        <xs:sequence>
          <xs:element maxOccurs="unbounded" ref="quantity"/>
          <xs:choice maxOccurs="unbounded">
            <xs:element ref="matrix_form"/>
            <xs:element ref="vector_form"/>
          </xs:choice>
        </xs:sequence>
      </xs:choice>
      <xs:attribute name="analysistype" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="quantity"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="matrix_form">
    <xs:complexType>
      <xs:attribute name="i" use="required" type="xs:integer"/>
      <xs:attribute name="j" use="required" type="xs:integer"/>
      <xs:attribute name="axi" use="required" type="xs:string"/>
      <xs:attribute name="planar" use="required" type="xs:string"/>
      <xs:attribute name="symmetric" type="xs:integer"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="vector_form">
    <xs:complexType>
      <xs:attribute name="i" use="required" type="xs:integer"/>
      <xs:attribute name="j" use="required" type="xs:integer"/>
      <xs:attribute name="planar" use="required" type="xs:string"/>
      <xs:attribute name="axi" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="essential_form">
    <xs:complexType>
      <xs:attribute name="i" use="required" type="xs:integer"/>
      <xs:attribute name="axi" use="required" type="xs:string"/>
      <xs:attribute name="planar" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="boundary">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="quantity"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="matrix_form"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="vector_form"/>
          <xs:element ref="essential_form"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LMSC-NTappy/agros2d/resources/modules/current.xml
<?xml version="1.0"?>
<module:module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="XMLModule ../xsd/module_xml.xsd" xmlns:module="XMLModule">

	<module:general id="current" name="Current field">
		<module:description>Electric current is a flow of electric charge
			through a medium. This charge is typically carried by moving
			electrons in a conductor such as wire. It can also be carried by ions
			in an electrolyte, or by both ions and electrons in a plasma.
		</module:description>
		<module:analyses>
			<module:analysis id="steadystate" type="steadystate"
				name="Steady state" solutions="1" />
		</module:analyses>
	</module:general>

	<module:constants />

	<module:volume>
		<module:quantity id="current_conductivity" shortname="cu_gamma" />

		<module:weakforms_volume>
			<module:weakform_volume analysistype="steadystate">
				<module:quantity id="current_conductivity" />

				<module:matrix_form i="1" j="1"
					planar_linear="cu_gamma * (udx * vdx + udy * vdy)" 
					axi_linear="cu_gamma * r * (udr * vdr + udz * vdz)"
					planar_newton="cu_gamma * (udx * vdx + udy * vdy)" 
					axi_newton="cu_gamma * r * (udr * vdr + udz * vdz)"
					symmetric="1" />

				<module:vector_form i="1" j="1" 
					planar_linear="0"
					axi_linear="0" 
					planar_newton="cu_gamma * (updx * vdx + updy * vdy)"
					axi_newton="cu_gamma * r * (updr * vdr + updz * vdz)" />
			</module:weakform_volume>
		</module:weakforms_volume>
	</module:volume>

	<module:surface>
		<module:quantity id="current_potential" shortname="cu_V" />
		<module:quantity id="current_inward_current_flow"
			shortname="cu_Jn" />

		<module:weakforms_surface>
			<module:weakform_surface analysistype="steadystate"
				default="current_potential">
				<module:boundary id="current_potential" name="Fixed voltage">
					<module:quantity id="current_potential" />

                    <module:essential_form i="1"
                        planar_linear="cu_V"
                        axi_linear="cu_V"
                        planar_newton="cu_V"
                        axi_newton="cu_V" />
				</module:boundary>

				<module:boundary id="current_inward_current_flow"
					name="Current density">
					<module:quantity id="current_inward_current_flow" />

					<module:vector_form i="1" j="1" 
						planar_linear="cu_Jn * vval"
						axi_linear="cu_Jn * r * vval" 
						planar_newton="- cu_Jn * vval"
						axi_newton="- cu_Jn * r * vval" />
				</module:boundary>
			</module:weakform_surface>
		</module:weakforms_surface>
	</module:surface>

	<module:preprocessor>
		<module:gui type="volume">
			<module:group>
				<module:quantity id="current_conductivity" name="Conductivity"
					shortname="gamma" shortname_html="&lt;i&gt;&amp;gamma;&lt;/i&gt;"
					shortname_latex="\gamma" unit="S/m" unit_html="S.m&lt;sup&gt;-1&lt;/sup&gt;"
					unit_latex="S \cdot m^{-1}" />
			</module:group>
		</module:gui>
		<module:gui type="surface">
			<module:group>
				<module:quantity id="current_potential" name="Fixed voltage"
					shortname="V" shortname_html="&lt;i&gt;&amp;phi;&lt;/i&gt;"
					shortname_latex="\phi" unit="V" unit_html="V" unit_latex="V" />
				<module:quantity id="current_inward_current_flow"
					name="Current density" shortname="Jn"
					shortname_html="&lt;i&gt;J&lt;/i&gt;&lt;sub&gt;n&lt;/sub&gt;"
					shortname_latex="J_\mathrm{n}" unit="A/m2" unit_html="A.m&lt;sup&gt;-2&lt;/sup&gt;"
					unit_latex="A \cdot m^{-2}" />
			</module:group>
		</module:gui>
	</module:preprocessor>

	<module:postprocessor>
		<module:localvariables>
			<module:localvariable id="current_potential"
				name="Scalar potential" type="scalar" shortname="V"
				shortname_html="&lt;i&gt;V&lt;/i&gt;" shortname_latex="V" unit="V"
				unit_html="V" unit_latex="V">
				<module:expression analysistype="steadystate"
					planar="value1" axi="value1" />
			</module:localvariable>
			<module:localvariable id="current_electric_field"
				name="Electric field" type="vector" shortname="E" shortname_html="&lt;i&gt;E&lt;/i&gt;"
				shortname_latex="E" unit="V/m" unit_html="V.m&lt;sup&gt;-1&lt;/sup&gt;"
				unit_latex="V \cdot m^{-1}">
				<module:expression analysistype="steadystate"
					planar_x="- dx1" planar_y="- dy1" axi_r="- dr1" axi_z="- dz1" />
			</module:localvariable>
			<module:localvariable id="current_current_density"
				name="Current density" type="vector" shortname="J"
				shortname_html="&lt;i&gt;J&lt;/i&gt;" shortname_latex="J" unit="A/m2"
				unit_html="A.m&lt;sup&gt;-2&lt;/sup&gt;" unit_latex="A \cdot m^{-2}">
				<module:expression analysistype="steadystate"
					planar_x="- cu_gamma * dx1" planar_y="- cu_gamma * dy1" axi_r="- cu_gamma * dr1"
					axi_z="- cu_gamma * dz1" />
			</module:localvariable>
			<module:localvariable id="current_joule_losses"
				name="Joule losses" type="scalar" shortname="pj"
				shortname_html="&lt;i&gt;p&lt;/i&gt;&lt;sub&gt;j&lt;/sub&gt;"
				shortname_latex="p_{j}" unit="W/m3" unit_html="W.m&lt;sup&gt;-3&lt;/sup&gt;"
				unit_latex="W \cdot m^{-3}">
				<module:expression analysistype="steadystate"
					planar="cu_gamma * (dx1 * dx1 + dy1 * dy1)" axi="cu_gamma * (dr1 * dr1 + dz1 * dz1)" />
			</module:localvariable>
			<module:localvariable id="current_conductivity"
				name="Conductivity" type="scalar" shortname="gamma"
				shortname_html="&lt;i&gt;&amp;gamma;&lt;/i&gt;" shortname_latex="\gamma"
				unit="S/m" unit_html="S.m&lt;sup&gt;-1&lt;/sup&gt;" unit_latex="S \cdot m^{-1}">
				<module:expression analysistype="steadystate"
					planar="cu_gamma" axi="cu_gamma" />
			</module:localvariable>
		</module:localvariables>

		<module:view>
			<module:scalar_view>
				<module:default analysistype="steadystate" id="current_potential" />
			</module:scalar_view>
			<module:vector_view>
				<module:default analysistype="steadystate"
					id="current_current_density" />
			</module:vector_view>
		</module:view>

		<module:volumeintegrals>
			<module:volumeintegral id="current_volume"
				name="Volume" shortname="V" shortname_html="&lt;i&gt;V&lt;/i&gt;"
				shortname_latex="V" unit="m3" unit_html="m&lt;sup&gt;3&lt;/sup&gt;"
				unit_latex="m^{3}">
				<module:expression analysistype="steadystate"
					planar="1.0" axi="2.0 * PI * r" />
			</module:volumeintegral>
			<module:volumeintegral id="current_cross_section"
				name="Cross section" shortname="S" shortname_html="&lt;i&gt;S&lt;/i&gt;"
				shortname_latex="S" unit="m2" unit_html="m&lt;sup&gt;2&lt;/sup&gt;"
				unit_latex="m^{2}">
				<module:expression analysistype="steadystate"
					planar="1.0" axi="1.0" />
			</module:volumeintegral>
			<module:volumeintegral id="current_joule_losses"
				name="Joule losses" shortname="Pj"
				shortname_html="&lt;i&gt;P&lt;/i&gt;&lt;sub&gt;j&lt;/sub&gt;"
				shortname_latex="P_{j}" unit="W" unit_html="W" unit_latex="W">
				<module:expression analysistype="steadystate"
					planar="cu_gamma * (dx1 * dx1 + dy1 * dy1)" axi="2.0 * PI * r * cu_gamma * (dr1 * dr1 + dz1 * dz1)" />
			</module:volumeintegral>
		</module:volumeintegrals>

		<module:surfaceintegrals>
			<module:surfaceintegral id="current_length"
				name="Length" shortname="l" shortname_html="&lt;i&gt;l&lt;/i&gt;"
				shortname_latex="l" unit="m" unit_html="m" unit_latex="m">
				<module:expression analysistype="steadystate"
					planar="1.0" axi="1.0" />
			</module:surfaceintegral>
			<module:surfaceintegral id="current_surface"
				name="Surface" shortname="S" shortname_html="&lt;i&gt;S&lt;/i&gt;"
				shortname_latex="S" unit="m2" unit_html="m&lt;sup&gt;2&lt;/sup&gt;"
				unit_latex="m^{2}">
				<module:expression analysistype="steadystate"
					planar="1.0" axi="2.0 * PI * r" />
			</module:surfaceintegral>
			<module:surfaceintegral id="current_current"
				name="Current" shortname="I" shortname_html="&lt;i&gt;I&lt;/i&gt;"
				shortname_latex="I" unit="A" unit_html="A" unit_latex="A">
				<module:expression analysistype="steadystate"
					planar="cu_gamma * (tanx * dy1 - tany * dx1)" axi="2.0 * PI * r * cu_gamma * (tanr * dz1 - tanz * dr1)" />
			</module:surfaceintegral>
		</module:surfaceintegrals>
	</module:postprocessor>
</module:module>

=== LMSC-NTappy/agros2d/resources/modules/flow.xml
<?xml version="1.0"?>
<module:module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="XMLModule ../xsd/module_xml.xsd" xmlns:module="XMLModule">

    <module:general id="flow" name="Incompressible flow">
        <module:description>Incompressible flow model using Navier-Stokes equations </module:description>
        <module:analyses>
            <module:analysis id="steadystate" type="steadystate" name="Steady state" solutions="3" />
            <module:analysis id="transient" type="transient" name="Transient" solutions="3"/>
        </module:analyses>
    </module:general>

    <module:constants />

    <module:volume>
        <module:quantity id="flow_viscosity" shortname="fl_mu" />
        <module:quantity id="flow_density" shortname="fl_rho" />

        <module:weakforms_volume>
            <module:weakform_volume analysistype="steadystate">
                <module:quantity id="flow_viscosity" />
                <module:quantity id="flow_density" />

                <module:matrix_form i="1" j="1"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="fl_mu * (udx * vdx + udy * vdy) + fl_rho * (value1 * udx + value2 * udy + dx1 * uval) * vval"
                    axi_newton=""
                />
                <module:matrix_form i="1" j="2"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="fl_rho * dy1 * uval * vval"
                    axi_newton=""
                />
                <module:matrix_form i="1" j="3"
                    planar_linear=""
                    axi_linear=""
                    planar_newton=" - uval * vdx"
                    axi_newton=""
                />
                <module:matrix_form i="2" j="1"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="fl_rho * dx2 * uval * vval"
                    axi_newton=""
                />
                <module:matrix_form i="2" j="2"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="fl_mu * (udx * vdx + udy * vdy) + fl_rho * (value1 * udx + value2 * udy + dy2 * uval) * vval"
                    axi_newton=""
                />
                <module:matrix_form i="2" j="3"
                    planar_linear=""
                    axi_linear=""
                    planar_newton=" - uval * vdy"
                    axi_newton=""
                />
                <!--                    asi ne!!-->
                <module:matrix_form i="3" j="1"
                    planar_linear=""
                    axi_linear=""
                    planar_newton=" uval * vdx"
                    axi_newton=""
                />
                <!--                    asi ne!!-->
                <module:matrix_form i="3" j="2"
                    planar_linear=""
                    axi_linear=""
                    planar_newton=" uval * vdy"
                    axi_newton=""
                />
                <module:matrix_form i="3" j="3"
                    planar_linear=""
                    axi_linear=""
                    planar_newton=""
                    axi_newton=""
                />

<!--                todo: proc je tam minus u tlaku? z puvodni rovnice pouziju green. vetu na laplase, tim by se melo obratit znamenko a tedy byt stejne pro viskozni cast jako pro tlak-->
                <module:vector_form i="1" j="1"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="fl_mu * (dx1 * vdx + dy1 * vdy) - value3 * vdx + fl_rho * (value1 * dx1 + value2 * dy1) * vval"
                    axi_newton=""
                />
                <module:vector_form i="1" j="2"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="0"
                    axi_newton=""
                />
                <module:vector_form i="1" j="3"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="0"
                    axi_newton=""
                />
                <module:vector_form i="2" j="1"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="0"
                    axi_newton=""
                />
                <module:vector_form i="2" j="2"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="fl_mu * (dx2 * vdx + dy2 * vdy) - value3 * vdy + fl_rho * (value1 * dx2 + value2 * dy2) * vval"
                    axi_newton=""
                />
                <module:vector_form i="2" j="3"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="0"
                    axi_newton=""
                />
                <module:vector_form i="3" j="1"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="0"
                    axi_newton=""
                />
                <module:vector_form i="3" j="2"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="0"
                    axi_newton=""
                />
                <module:vector_form i="3" j="3"
                    planar_linear=""
                    axi_linear=""
                    planar_newton="0"
                    axi_newton=""
                />

            </module:weakform_volume>
        </module:weakforms_volume>
    </module:volume>

    <module:surface>
        <module:quantity id="elasticity_displacement_x" shortname="st_dx" />

        <module:weakforms_surface>
            <module:weakform_surface analysistype="steadystate" default="elasticity_fixed_fixed">
                <module:boundary id="elasticity_fixed_fixed" name="Fixed - fixed">
                    <module:quantity id="elasticity_displacement_x" />
                    <module:quantity id="elasticity_displacement_y" />

                    <module:essential_form i="1"
                        planar_linear="st_dx"
                        axi_linear="st_dx"
                        planar_newton="st_dx"
                        axi_newton="st_dx" />
                    <module:essential_form i="2"
                        planar_linear="st_dy"
                        axi_linear="st_dy"
                        planar_newton="st_dy"
                        axi_newton="st_dy" />
                </module:boundary>

            </module:weakform_surface>
        </module:weakforms_surface>
    </module:surface>

    <module:preprocessor>
        <module:gui type="volume">
            <module:group>
				<module:quantity id="elasticity_young_modulus" name="Young modulus"
					shortname="E" shortname_html="&lt;i&gt;E&lt;/i&gt;"
					shortname_latex="E" unit="Pa" unit_html="Pa" unit_latex="Pa" />
            </module:group>
        </module:gui>
        <module:gui type="surface">
            <module:group>
				<module:quantity id="elasticity_displacement_x"
					name="Fixed - x" shortname="dx"
					shortname_html="&lt;i&gt;&amp;delta;&lt;/i&gt;&lt;sub&gt;x&lt;/sub&gt;"
					shortname_latex="\delta_\mathrm{x}" unit="m" unit_html="m"
					unit_latex="m" />
            </module:group>
        </module:gui>
    </module:preprocessor>

    <module:postprocessor>
        <module:localvariables>
            <module:localvariable id="elasticity_displacement"
                                name="Displacement" type="vector" shortname="d" shortname_html="&lt;i&gt;d&lt;/i&gt;"
				shortname_latex="d" unit="m" unit_html="m" unit_latex="m">
				<module:expression analysistype="steadystate"
					planar_x="value1" planar_y="value2" axi_r="value1" axi_z="value2" />
            </module:localvariable>
        </module:localvariables>

        <module:view>
            <module:scalar_view>
                <module:default analysistype="steadystate" id="elasticity_displacement" />
            </module:scalar_view>
            <module:vector_view>
                <module:default analysistype="steadystate" id="elasticity_displacement" />
            </module:vector_view>
        </module:view>

        <module:volumeintegrals>
            <module:volumeintegral id="elasticity_volume"
				name="Volume" shortname="V" shortname_html="&lt;i&gt;V&lt;/i&gt;"
				shortname_latex="V" unit="m3" unit_html="m&lt;sup&gt;3&lt;/sup&gt;"
				unit_latex="m^{3}">
				<module:expression analysistype="steadystate"
					planar="1.0" axi="2.0 * PI * r" />
            </module:volumeintegral>
        </module:volumeintegrals>

        <module:surfaceintegrals>
            <module:surfaceintegral id="elasticity_length"
				name="Length" shortname="l" shortname_html="&lt;i&gt;l&lt;/i&gt;"
				shortname_latex="l" unit="m" unit_html="m" unit_latex="m">
				<module:expression analysistype="steadystate"
					planar="1.0" axi="1.0" />
            </module:surfaceintegral>
        </module:surfaceintegrals>

        <module:force />
    </module:postprocessor>
</module:module>
